title: Data Science Portfolio 
logo: /assets/images/Stickperson.jfif
description: Time Machine is a theme for GitHub Pages.
#description: text below image 
show_downloads: true
theme: jekyll-theme-time-machine
