title: Data Science Portfolio 
logo: C:\Users\nitsca\OneDrive - Cambridge\Desktop\Anita at OCR - 2020+\Apprenticeship\L6_BSc (BPP)\Module 5 - Data Science Professional Practice\Txx - Assessment\Images\Stickperson.jfif
#description: text below image 
show_downloads: true 
theme: jekyll-theme-minimal 
