s/title: Data Science Portfolio 
logo: /assets/images/Stickperson.jfif
description: This GitHub page has been created for educational purposes only as required by the summative assessment for my studies of ‘Data Science Professional Practice’. To protect my privacy, I will stay anonymous.
#description: text below image 
show_downloads: false
theme: jekyll-theme-time-machine
baseurl: /BPP_L6_BSc_M5
- "assets/images"
